version: '2'

services:
  cms:
    image: drupal # this will use drupal latest
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  datasource:
    image: postgres  # this will use postgres latest
    environment:
      - POSTGRES_PASSWORD=mypasswd
